version: "3"

networks:
  docker_lnnet:
    external: true

volumes:
  thunderdrone_db:

services:
  thunderdrone-app:
    build: ./
    container_name: thunderdrone-app
    networks:
      - docker_lnnet
    ports:
      - "8080:8080"
    depends_on:
      - "thunderdrone-db"
    command: ["./wait-for-it.sh", "thunderdrone-db:5432", "--", "echo", "database is up!"]

  thunderdrone-ui:
    build: ./web
    container_name: thunderdrone-web
    networks:
      - docker_lnnet
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app:delegated
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - "thunderdrone-app"
  thunderdrone-db:
    image: "timescale/timescaledb:latest-pg14"
    environment:
      POSTGRES_PASSWORD: "password"
    networks:
      - docker_lnnet
    ports:
      - "5432:5432"
    volumes:
      -   thunderdrone_db:/var/lib/postgresql/data
